apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo
  namespace: demo-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: argocd-demo
  template:
    metadata:
      labels:
        app: argocd-demo
    spec:
      containers:
      - name: argocd-demo
        image: shansk007/argocd-demo:v3
        ports:
        - containerPort: 3000
